// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test2/test2.proto

package test2

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Test2 struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Test2) Reset()         { *m = Test2{} }
func (m *Test2) String() string { return proto.CompactTextString(m) }
func (*Test2) ProtoMessage()    {}
func (*Test2) Descriptor() ([]byte, []int) {
	return fileDescriptor_6eaf09c5ad70f95a, []int{0}
}
func (m *Test2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Test2.Unmarshal(m, b)
}
func (m *Test2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Test2.Marshal(b, m, deterministic)
}
func (dst *Test2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Test2.Merge(dst, src)
}
func (m *Test2) XXX_Size() int {
	return xxx_messageInfo_Test2.Size(m)
}
func (m *Test2) XXX_DiscardUnknown() {
	xxx_messageInfo_Test2.DiscardUnknown(m)
}

var xxx_messageInfo_Test2 proto.InternalMessageInfo

func (m *Test2) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*Test2)(nil), "example.test2.Test2")
}

func init() { proto.RegisterFile("test2/test2.proto", fileDescriptor_6eaf09c5ad70f95a) }

var fileDescriptor_6eaf09c5ad70f95a = []byte{
	// 85 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x49, 0x2d, 0x2e,
	0x31, 0xd2, 0x07, 0x93, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xbc, 0xa9, 0x15, 0x89, 0xb9,
	0x05, 0x39, 0xa9, 0x7a, 0x60, 0x41, 0x25, 0x71, 0x2e, 0xd6, 0x10, 0x10, 0x43, 0x88, 0x8f, 0x8b,
	0x29, 0x33, 0x45, 0x82, 0x51, 0x81, 0x51, 0x83, 0x39, 0x88, 0x29, 0x33, 0xc5, 0x89, 0x3d, 0x8a,
	0x15, 0xac, 0x22, 0x89, 0x0d, 0xac, 0xcf, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x73, 0xf6, 0xcc,
	0x49, 0x4c, 0x00, 0x00, 0x00,
}
